AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - config/initializers/*
    - config/environments/*
    - bin/*
    - config/puma.rb
    - config/routes.rb
    - Gemfile

  TargetRubyVersion: 2.5.1

Metrics/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/BlockComments:
  Enabled: false

NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Style/RaiseArgs:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
